#ifndef MAPVIZ_PLUGINS_AUTOPILOT_WAYPOINTS_PLUGIN_H_
#define MAPVIZ_PLUGINS_AUTOPILOT_WAYPOINTS_PLUGIN_H_

// C++ standard libraries
#include <string>
#include <list>

#include <mapviz/mapviz_plugin.h>

// QT libraries
#include <QGLWidget>
#include <QObject>
#include <QWidget>

// ROS libraries
#include <ros/ros.h>
#include <tf/transform_datatypes.h>
#include <geographic_msgs/GeoPath.h>
#include <autopilot_msgs/ModifyGPSWaypoint.h>

#include <mapviz/map_canvas.h>
#include <mapviz_plugins/point_drawing_plugin.h>

// QT autogenerated files
#include "ui_autopilot_waypoints_config.h"

namespace mapviz_plugins
{
  class AutopilotWaypointsPlugin : public mapviz::MapvizPlugin
  {
    Q_OBJECT

   public:
    AutopilotWaypointsPlugin();
    virtual ~AutopilotWaypointsPlugin();

    bool Initialize(QGLWidget* canvas);
    void Shutdown()
    {
    }

    void Paint(QPainter* painter, double x, double y, double scale);
    void Draw(double x, double y, double scale);
    void Transform() { };

    void LoadConfig(const YAML::Node& node, const std::string& path);
    void SaveConfig(YAML::Emitter& emitter, const std::string& path);

    QWidget* GetConfigWidget(QWidget* parent);

    void PrintError(const std::string& message);
    void PrintInfo(const std::string& message);
    void PrintWarning(const std::string& message);

    bool SupportsPainting()
    {
      return true;
    }

    protected:
    bool eventFilter(QObject* object, QEvent* event);
    bool handleMousePress(QMouseEvent*);
    bool handleMouseRelease(QMouseEvent*);
    bool handleMouseMove(QMouseEvent*);
    void waypointsCallback(const geographic_msgs::GeoPathConstPtr& waypoints);

    protected Q_SLOTS:
    void Clear();
    void SelectTopic();
    void TopicEdited();
    void AlphaChanged(double) { };

    private:
    Ui::autopilot_waypoints_config ui_;
    QWidget* config_widget_;

    std::string topic_;
    bool has_message_;

    mapviz::MapCanvas* map_canvas_;
    tf::Vector3 last_position_;
    ros::Subscriber waypoints_sub_;
    ros::ServiceClient modify_waypoints_client_;

    std::vector<tf::Vector3> vertices_;
    std::vector<tf::Vector3> transformed_vertices_;

    int selected_point_;
    bool is_mouse_down_;
    QPointF mouse_down_pos_;
    qint64 mouse_down_time_;

    qint64 max_ms_;
    qreal max_distance_;
    };

    }

    #endif // MAPVIZ_PLUGINS_MEASURING_PLUGIN_H_
