#ifndef MAPVIZ_PLUGINS_AUTOPILOT_AUTO_MANUAL_BUTTON_PLUGIN_H_
#define MAPVIZ_PLUGINS_AUTOPILOT_AUTO_MANUAL_BUTTON_PLUGIN_H_

#include <mapviz/mapviz_plugin.h>

// ROS libraries
#include <ros/ros.h>
#include <std_msgs/Bool.h>

// Mapviz libraries
#include <mapviz/map_canvas.h>
//
// QT autogenerated files
#include "ui_autopilot_auto_manual_button_config.h"

namespace mapviz_plugins
{
  class AutopilotAutoManualButtonPlugin : public mapviz::MapvizPlugin
  {
    Q_OBJECT

   public:
    AutopilotAutoManualButtonPlugin();
    virtual ~AutopilotAutoManualButtonPlugin();

    bool Initialize(QGLWidget* canvas);
    void Shutdown()
    {
    }

    void Draw(double x, double y, double scale);
    void Transform() { };

    void LoadConfig(const YAML::Node& node, const std::string& path);
    void SaveConfig(YAML::Emitter& emitter, const std::string& path);

    QWidget* GetConfigWidget(QWidget* parent);

    void PrintError(const std::string& message);
    void PrintInfo(const std::string& message);
    void PrintWarning(const std::string& message);

    bool SupportsPainting()
    {
      return true;
    }

    protected Q_SLOTS:
    void AutomaticMode();
    void ManualMode();

    private:
    Ui::autopilot_auto_manual_button_config ui_;
    QWidget* config_widget_;
    QPalette p_auto_, p_manual_;
    mapviz::MapCanvas* map_canvas_;

    ros::Publisher pause_navigation_pub_;

    bool is_auto_, is_manual_;
    };

    }

    #endif // MAPVIZ_PLUGINS_AUTOPILOT_EMERGENCY_BUTTON_PLUGIN_H_
