#ifndef MAPVIZ_PLUGINS_AUTOPILOT_MISSION_PLUGIN_H_
#define MAPVIZ_PLUGINS_AUTOPILOT_MISSION_PLUGIN_H_

#include <mapviz/mapviz_plugin.h>

// ROS libraries
#include <ros/ros.h>
#include <std_msgs/Bool.h>
#include <nav_msgs/Path.h>
#include <std_srvs/SetBool.h>

// Mapviz libraries
#include <mapviz/map_canvas.h>
//
// QT autogenerated files
#include "ui_autopilot_mission_config.h"

namespace mapviz_plugins
{
  class AutopilotMissionPlugin : public mapviz::MapvizPlugin
  {
    Q_OBJECT

   public:
    AutopilotMissionPlugin();
    virtual ~AutopilotMissionPlugin();

    bool Initialize(QGLWidget* canvas);
    void Shutdown()
    {
    }

    void Draw(double x, double y, double scale);
    void Transform() { };

    void LoadConfig(const YAML::Node& node, const std::string& path);
    void SaveConfig(YAML::Emitter& emitter, const std::string& path);

    QWidget* GetConfigWidget(QWidget* parent);

    void PrintError(const std::string& message);
    void PrintInfo(const std::string& message);
    void PrintWarning(const std::string& message);

    bool SupportsPainting()
    {
      return true;
    }

    protected Q_SLOTS:
    void MissionPlanCB(const nav_msgs::Path &msg);
    void SwarmEventCB(const nav_msgs::Path &msg);
    void AcceptMissionPlan();
    void AcceptSwarmEvent();
    void flashingMissionPlan(const ros::TimerEvent& event);
    void flashingSwarmEvent(const ros::TimerEvent& event);

    private:
    Ui::autopilot_mission_config ui_;
    QWidget* config_widget_;
    QPalette p_text_;
    mapviz::MapCanvas* map_canvas_;

    ros::Timer mission_plan_timer_, swarm_event_timer_;

    ros::Subscriber mission_plan_debug_sub_, swarm_event_debug_sub_;
    ros::ServiceClient confirm_mission_plan_, confirm_swarm_event_;

    bool mission_plan_flashing_ = false, swarm_event_flashing_ = false;
    };

    }

    #endif // MAPVIZ_PLUGINS_AUTOPILOT_MISSION_PLUGIN_H_
